  # vaultwarden
  # nextcloud
  # minecraft
  # backupstrategie
  # fail2ban
  # guacamole
  # huly.io
  # samba

services:
  nginx-reverse-proxy:
    image: nginx:latest
    container_name: infrastructure_nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy-network

  apache:
    image: httpd:latest
    container_name: infrastructure_apache
    restart: always
    volumes:
      - ./apache2/htdocs:/usr/local/apache2/htdocs:ro
    networks:
      - proxy-network

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: infrastructure_gitlab
    restart: always
    depends_on:
      - nginx-reverse-proxy
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.laurenzschmidt.de'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "2222:22"
    volumes:
      - ./certs:/etc/gitlab/ssl:ro
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - proxy-network

  jenkins:
    container_name: infrastructure_jenkins
    restart: always
    depends_on:
      - nginx-reverse-proxy
    build:
      dockerfile: jenkins-docker
    volumes:
      - ./certs:/etc/jenkins/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  jenkins_home:
  vaultwarden-data:
